### ISSUE TITLE
不好意思，打扰了，借楼问个问题

### ISSUE THREAD

**Issue by huangsheng7271** [yuezk/github-account-switcher#1]
大佬，你chatgpt-mirror这个项目的前端部分（_next/static/）那部分打包前的源码出售吗

**Comment by yuezk** [comment]
现在那么多更好的 UI 出来了，为啥不用，偏要用这个套壳的

**Comment by huangsheng7271** [comment]
就喜欢和官网几乎完全一致的风格，原教旨大佬，出售吗




ζ&nbsp;在路上╰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuezk/github-account-switcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月9日(星期天) 凌晨0:06
***@***.***&gt;;
抄送:&nbsp;"ζ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuezk/github-account-switcher] 不好意思，打扰了，借楼问个问题 (Issue #1)





 
现在那么多更好的 UI 出来了，为啥不用，偏要用这个套壳的

**Comment by yuezk** [comment]
你可能误会了。我并没有 _next/static 里面对应的源码，我的做法比较简单粗暴，直接保存的官方的静态资源，然后用 hack 的方式加了几个菜单项和弹窗。

**Comment by huangsheng7271** [comment]
大佬，你这种hack方式能自定义到什么程度，能到有了源码那样自定义的程度吗

**Comment by yuezk** [comment]
肯定到不了，没有办法长期维护，功能需求复杂的话，靠 hack 的方式就不好使了。如果真觉得官方的 UI 有感觉可以从头模仿一个。官方主要用的框架是 nextjs, tailwind css 和 headless ui

**Comment by huangsheng7271** [comment]
好的，谢谢


ζ&nbsp;在路上╰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuezk/github-account-switcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月9日(星期天) 中午1:28
***@***.***&gt;;
抄送:&nbsp;"ζ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuezk/github-account-switcher] 不好意思，打扰了，借楼问个问题 (Issue #1)





 
肯定到不了，没有办法长期维护，功能需求复杂的话，靠 hack 的方式就不好使了。如果真觉得官方的 UI 有感觉可以从头模仿一个。官方主要用的框架是 nextjs, tailwind css 和 headless ui

**Comment by huangsheng7271** [comment]
大佬，能加个你的联系方式吗，有个问题想咨询你，可以付费咨询你吗。你fastgpt这个项目是怎么把官方的源码和你自己的代码混合在一起的



好的，谢谢


ζ 在路上╰
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yuezk/github-account-switcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月9日(星期天) 中午1:28
***@***.***&gt;;
抄送:&nbsp;"ζ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuezk/github-account-switcher] 不好意思，打扰了，借楼问个问题 (Issue #1)





 
肯定到不了，没有办法长期维护，功能需求复杂的话，靠 hack 的方式就不好使了。如果真觉得官方的 UI 有感觉可以从头模仿一个。官方主要用的框架是 nextjs, tailwind css 和 headless ui

**Comment by yuezk** [comment]
![image](https://github.com/yuezk/github-account-switcher/assets/3297602/cb790eff-dba8-4e53-bb78-50b78d760398)
