### ISSUE TITLE
Include in the README how it's working

### ISSUE THREAD

**Issue by arxpoetica** [yuezk/github-account-switcher#5]
First off, love the plugin. Was looking for a way to have multiple accounts today, and THIS SOLVED MY PROBLEM.

I wonder if you could include a brief something in the README that explains how it works? I'm super curious. I'll probably read the source code to see if I can figure it out, but it might be good for the next traveler to know how.

**Comment by jakenvac** [comment]
I did a little reverse engineering today to fix a bug. My understanding is that the core behavior is simply swapping out the cookies for each account and reloading the page.

**Comment by yuezk** [comment]
Added in https://github.com/yuezk/github-account-switcher?tab=readme-ov-file#how-it-works
