### ISSUE TITLE
GitHub is changing the navigation and the extension doesn't work in the new sidebar design

### ISSUE THREAD

**Issue by rwasef1830** [yuezk/github-account-switcher#6]
Hello
GitHub is rolling out in feature preview a new design. This new design changes the navigation to use a sidebar flyout instead of the normal dropdown, and the user account switching doesn't show up in it.

**Comment by yuezk** [comment]
Confirmed, will support it soon.

**Comment by rwasef1830** [comment]
Thank you so much!

**Comment by yuezk** [comment]
Webstore review passed, closing it.
